export enum HumanLikeBrainEvent {
  MESSAGES_RECEIVED = 'MESSAGES_RECEIVED',
  BEGIN_LOOKING_FOR_MESSAGES_TO_ENGAGE = 'BEGIN_LOOKING_FOR_MESSAGES_TO_ENGAGE',
  FOUND_NO_MESSAGES = 'FOUND_NO_MESSAGES',
  ENGAGE_MESSAGE = 'ENGAGE_MESSAGE',
  START_READING_MESSAGE = 'START_READING_MESSAGE',
  GIVE_UP_AFTER_READING_MESSAGE = 'GIVE_UP_AFTER_READING_MESSAGE',
  START_TYPING_REPLY = 'START_TYPING_REPLY',
  FINISHED_REPLYING = 'FINISHED_REPLYING',
}
