export enum HumanLikeBrainState {
  IDLE = 'IDLE',
  LOOKING_FOR_MESSAGE_TO_ENGAGE = 'LOOKING_FOR_MESSAGE_TO_ENGAGE',
  BEGINNING_ENGAGING_MESSAGE = 'BEGINNING_ENGAGING_MESSAGE',
  READING_MESSAGE = 'READING_MESSAGE',
  TYPING_ANSWER = 'TYPING_ANSWER',
}
